[package]
name = "filebuffer"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
license = "Apache-2.0"
readme = "readme.md"
keywords = ["non-blocking", "memory-mapped", "file", "input", "prefetch"]
description = "Fast and simple file reading"
repository = "https://github.com/ruud-v-a/filebuffer"
documentation = "https://ruud-v-a.github.io/filebuffer/doc/v0.1.0/filebuffer/"

[target.'cfg(unix)'.dependencies]
libc = "0.2.6"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.1"
winapi = "0.2.5"

[dev-dependencies]
rust-crypto = "0.2.34"
