[package]

name = "filebuffer"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
license = "Apache-2.0"
description = "Fast and simple file reading"

[dependencies]
# TODO: Depend only on libc for Unix-like platforms, and on winapi on Windows
# once RFC 1361 lands.
# https://github.com/rust-lang/rfcs/blob/master/text/1361-cargo-cfg-dependencies.md
libc = "0.2.6"
kernel32-sys = "0.2.1"
winapi = "0.2.5"

[dev-dependencies]
rust-crypto = "0.2.34"
